<a href="https://colab.research.google.com/github/arunnivas85/AL_ML/blob/main/L11_Live_Coding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Case Study: Analyzing Food Delivery Performance

We have been given a core business question from our operations team:
> **"Which city had the highest average order value last month, among orders that were not cancelled?"**

To solve this, we must break this human English request down into logical data steps.

### The 3-Step Analytical Pipeline:
1. **Filter:** Kick out any orders that were cancelled (and focus on last month's timeframe).
2. **Aggregate:** Group the remaining orders by `city` and calculate the average (`AVG` / `mean`) order cost.
3. **Sort & Extract:** Sort the list from highest average cost to lowest, and take the top result.

In [84]:
import pandas as pd

# Load the Superstore-style dataset
data = {
    'order_id': ['O1','O2','O3','O4','O5','O6','O7','O8'],
    'city': ['Mumbai','Delhi','Mumbai','Bangalore','Delhi','Mumbai','Delhi','Bangalore'],
    'category': ['Tech','Furniture','Tech','Office','Tech','Furniture','Office','Tech'],
    'sales': [25000, 8000, 15000, 3000, 32000, 12000, 5500, 18000],
    'profit': [5000, -500, 3200, 800, 8000, 1200, 600, 4000],
    'status': ['completed','completed','completed','cancelled','completed','completed','cancelled','completed']
}
df = pd.DataFrame(data)
print(df)

  order_id       city   category  sales  profit     status
0       O1     Mumbai       Tech  25000    5000  completed
1       O2      Delhi  Furniture   8000    -500  completed
2       O3     Mumbai       Tech  15000    3200  completed
3       O4  Bangalore     Office   3000     800  cancelled
4       O5      Delhi       Tech  32000    8000  completed
5       O6     Mumbai  Furniture  12000    1200  completed
6       O7      Delhi     Office   5500     600  cancelled
7       O8  Bangalore       Tech  18000    4000  completed

In [85]:
df.groupby("status")["sales"].sum()

#df.groupby("Status")["sales"].sum()

status
cancelled      8500
completed    110000
Name: sales, dtype: int64

In [4]:
df[['order_id', 'status', 'profit']]

  order_id     status  profit
0       O1  completed    5000
1       O2  completed    -500
2       O3  completed    3200
3       O4  cancelled     800
4       O5  completed    8000
5       O6  completed    1200
6       O7  cancelled     600
7       O8  completed    4000

In [7]:
df[df['sales'] > 10000][['order_id', 'sales']]


df[df["sales"]>10000][["order_id","sales"]]

# select order_id, sales from data where sales > 10000

  order_id  sales
0       O1  25000
2       O3  15000
4       O5  32000
5       O6  12000
7       O8  18000

# Q1: Show all completed orders from Mumbai

In [9]:
# Pandas
#result = df[(df['status'] == 'completed') & (df['city'] == 'Mumbai')]
#print(result[['order_id','city','sales','profit']])


result=df[ (df["status"]=='completed') & (df["city"]=="Mumbai")]
print(result)

  order_id    city   category  sales  profit     status
0       O1  Mumbai       Tech  25000    5000  completed
2       O3  Mumbai       Tech  15000    3200  completed
5       O6  Mumbai  Furniture  12000    1200  completed

-- SQL equivalent

```
SELECT order_id, city, sales, profit
FROM orders
WHERE status = 'completed'
  AND city = 'Mumbai';

 # Q2. Top 3 orders by sales

In [86]:
# Pandas
top3 = df.sort_values('sales', ascending=False).head(3)
print(top3[['order_id','city','sales']])

  order_id       city  sales
4       O5      Delhi  32000
0       O1     Mumbai  25000
7       O8  Bangalore  18000

In [10]:
top3=df.sort_values("sales",ascending=False).head(3)
print(top3)

  order_id       city category  sales  profit     status
4       O5      Delhi     Tech  32000    8000  completed
0       O1     Mumbai     Tech  25000    5000  completed
7       O8  Bangalore     Tech  18000    4000  completed

-- SQL equivalent

```
SELECT order_id, city, sales
FROM orders
ORDER BY sales DESC
LIMIT 3;

In [ ]:
df[(df['sales'] > 10000) & (df['status'] == 'completed')]

In [ ]:
df.sort_values(['city', 'sales'], ascending=[True, False])
# All cities sorted A-Z; within each city, sales sorted highest first

**SQL Equvivalent**

SELECT *
FROM data
ORDER BY city ASC, sales DESC;

In [ ]:
# --- isin filter ---
# Orders from metro cities only
metros = ['Mumbai', 'Delhi']
metro_orders = df[df['city'].isin(metros)]
print("\nMetro orders:")
print(metro_orders)

SELECT *
FROM data
WHERE city IN ('Mumbai', 'Delhi');

In [ ]:
~(df['category'] == "Furniture")

In [ ]:
# --- NOT filter ---
# All orders that are NOT Furniture
non_furniture_order = df[~(df['category'] == 'Furniture')]
print("\n non_furniture orders:", len(non_furniture_order))

In [83]:
non_furniture_orders=df[~(df["category"]=='Furniture')]
print(non_furniture_orders)

KeyError: 'category'

In [ ]:
non_furniture_order

We have 8 orders.

Can you tell me:

* Total sales from Mumbai?
* Total sales from Delhi?
* Total sales from Bangalore?

**GroupBy**:

GroupBy means dividing data into groups based on a column and then performing calculations on each group.

In [87]:
df.groupby("city")["sales"].sum()

city
Bangalore    21000
Delhi        45500
Mumbai       52000
Name: sales, dtype: int64

groupby() does NOT calculate anything.

It only separates rows into buckets.

Mumbai
----------------
O1   25000

O3   15000

O6   12000


Delhi
----------------
O2    8000

O5   32000

O7    5500


Bangalore
----------------
O4    3000

O8   18000

In [88]:
group_city = df.groupby("city")["sales"].sum()
print(group_city)

city
Bangalore    21000
Delhi        45500
Mumbai       52000
Name: sales, dtype: int64

In [101]:
group_city1 = df.groupby("city")

print(group_city1.groups)

{'Bangalore': [3, 7], 'Delhi': [1, 4, 6], 'Mumbai': [0, 2, 5]}

In [102]:
for city, group in group_city1:
  print("City: ", city)
  print("Group: ", group)
  print("-------------------------------------------------")

City:  Bangalore
Group:    order_id       city category  sales  profit     status
3       O4  Bangalore   Office   3000     800  cancelled
7       O8  Bangalore     Tech  18000    4000  completed
-------------------------------------------------
City:  Delhi
Group:    order_id   city   category  sales  profit     status
1       O2  Delhi  Furniture   8000    -500  completed
4       O5  Delhi       Tech  32000    8000  completed
6       O7  Delhi     Office   5500     600  cancelled
-------------------------------------------------
City:  Mumbai
Group:    order_id    city   category  sales  profit     status
0       O1  Mumbai       Tech  25000    5000  completed
2       O3  Mumbai       Tech  15000    3200  completed
5       O6  Mumbai  Furniture  12000    1200  completed
-------------------------------------------------

In [74]:
for city, group in group_city:
  print("City:", city)
  print("Group:", group)

TypeError: cannot unpack non-iterable int object

In [ ]:
"o1"+"o2"+"o3"

### **Sum Sales By City**

In [ ]:
df.groupby("city")["sales"].sum()

In [ ]:
df.groupby("city")["profit"].sum()

### **Which city has most orders?**

In [22]:
df.groupby("city")["order_id"].size()

# size

city
Bangalore    2
Delhi        3
Mumbai       3
Name: order_id, dtype: int64

### **Which city generates highest average order value?**

In [23]:
df.groupby("city")["sales"].mean()

city
Bangalore    10500.000000
Delhi        15166.666667
Mumbai       17333.333333
Name: sales, dtype: float64

### **Which category is most profitable?**

In [25]:
df.groupby("category")["profit"].sum()

category
Furniture      700
Office        1400
Tech         20200
Name: profit, dtype: int64

In [31]:
city_sales = df.groupby("city")["sales"].sum()
#print(city_sales)

for city in city_sales:
  print("City: \n", city)
#   print("Values: \n", sales)
#   print("-----------------------------------------------------------------------")

City:
 21000
City:
 45500
City:
 52000

# **Multiple Aggregations**

In [32]:
df.groupby('city')['sales'].agg(['sum', 'mean', 'count', 'max', 'min'])

             sum          mean  count    max    min
city
Bangalore  21000  10500.000000      2  18000   3000
Delhi      45500  15166.666667      3  32000   5500
Mumbai     52000  17333.333333      3  25000  12000

In [34]:
df.groupby("city")["sales"].agg(['sum','max','min','mean','count'])

             sum    max    min          mean  count
city
Bangalore  21000  18000   3000  10500.000000      2
Delhi      45500  32000   5500  15166.666667      3
Mumbai     52000  25000  12000  17333.333333      3

In [35]:
df.groupby("city").agg(
    sales_sum=("sales","sum"),
    profit_mean=("profit","mean"),
    total_count=("order_id","count")
)

           sales_sum  profit_mean  total_count
city
Bangalore      21000  2400.000000            2
Delhi          45500  2700.000000            3
Mumbai         52000  3133.333333            3

In [36]:
df.groupby("city").agg(
    sales_Sum=("sales","sum"),
    profit_count=("profit","count"),
    total_mean=("profit","mean")
)

           sales_Sum  profit_count   total_mean
city
Bangalore      21000             2  2400.000000
Delhi          45500             3  2700.000000
Mumbai         52000             3  3133.333333

In [38]:
df.groupby("city").agg({
    "sales": "sum",
    "profit": "sum",
    "order_id": "count"
})

           sales  profit  order_id
city
Bangalore  21000    4800         2
Delhi      45500    8100         3
Mumbai     52000    9400         3

### **Multiple GroupBy Columns**

### Sales by City and Category

Now management wants to know:

How much revenue does each category generate within each city?

In [46]:
cat_city = df.groupby(
    ["city", "category"]
)["sales"].sum()

print(cat_city)

city       category
Bangalore  Office        3000
           Tech         18000
Delhi      Furniture     8000
           Office        5500
           Tech         32000
Mumbai     Furniture    12000
           Tech         40000
Name: sales, dtype: int64

In [72]:
cat_city.groups

AttributeError: 'Series' object has no attribute 'groups'

In [ ]:
df.groupby(
    ["city", "category"]
)["sales"].sum()

The answer is correct.

But it is difficult to compare categories across cities.

Let's improve the presentation.

In [47]:
import pandas as pd

df = pd.DataFrame({
    "city":["Chennai","Chennai","Mumbai","Mumbai","Delhi"],
    "sales":[100,200,300,400,500]
})

print(df)

      city  sales
0  Chennai    100
1  Chennai    200
2   Mumbai    300
3   Mumbai    400
4    Delhi    500

In [48]:
df.groupby("city")["sales"].agg("mean")

city
Chennai    150.0
Delhi      500.0
Mumbai     350.0
Name: sales, dtype: float64

In [50]:
df.groupby("city")["sales"].transform("mean")

0    150.0
1    150.0
2    350.0
3    350.0
4    500.0
Name: sales, dtype: float64

In [52]:
df["city_avg"] = (
    df.groupby("city")["sales"]
      .transform("mean")
)
print(df)

      city  sales  city_avg
0  Chennai    100     150.0
1  Chennai    200     150.0
2   Mumbai    300     350.0
3   Mumbai    400     350.0
4    Delhi    500     500.0

In [54]:
df.groupby("city")["sales"].transform("mean")

0    150.0
1    150.0
2    350.0
3    350.0
4    500.0
Name: sales, dtype: float64

In [ ]:
df

In [ ]:
df

In [63]:
import pandas as pd

# Load
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
# Alternatively: df = pd.read_csv('titanic.csv')

print("Shape:", df.shape)
print("\n--- First look ---")
df.head(50)

Shape: (891, 12)

--- First look ---

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.0,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.0,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.0,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.0,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.0,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.0,1,0,2651,11.2417,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.0,1,0,7546,9.4750,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann ...",female,27.0,1,0,11668,21.0000,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.0,1,2,SC/Paris 2123,41.5792,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.0,0,0,330958,7.8792,NaN,Q
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.0,1,0,349237,17.8000,NaN,S

In [56]:
df.groupby("Pclass")["Age"].agg("mean")

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [57]:
df.groupby("Pclass")["Age"].transform("mean")

0      25.140620
1      38.233441
2      25.140620
3      38.233441
4      25.140620
         ...
886    29.877630
887    38.233441
888    25.140620
889    38.233441
890    25.140620
Name: Age, Length: 891, dtype: float64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [71]:
df["Age"] = df["Age"].fillna(
    df.groupby("Pclass")["Age"]
           .transform("mean")
)

print(df["Age"].head(60))

0     22.000000
1     38.000000
2     26.000000
3     35.000000
4     35.000000
5     25.140620
6     54.000000
7      2.000000
8     27.000000
9     14.000000
10     4.000000
11    58.000000
12    20.000000
13    39.000000
14    14.000000
15    55.000000
16     2.000000
17    29.877630
18    31.000000
19    25.140620
20    35.000000
21    34.000000
22    15.000000
23    28.000000
24     8.000000
25    38.000000
26    25.140620
27    19.000000
28    25.140620
29    25.140620
30    40.000000
31    38.233441
32    25.140620
33    66.000000
34    28.000000
35    42.000000
36    25.140620
37    21.000000
38    18.000000
39    14.000000
40    40.000000
41    27.000000
42    25.140620
43     3.000000
44    19.000000
45    25.140620
46    25.140620
47    25.140620
48    25.140620
49    18.000000
50     7.000000
51    21.000000
52    49.000000
53    29.000000
54    65.000000
55    38.233441
56    21.000000
57    28.500000
58     5.000000
59    11.000000
Name: Age, dtype: float64

In [ ]:
df.info()

In [90]:
import numpy as np

# a = np.array([1,2,3,4,5])
# print(a)

# z=np.zeros((3,4))
# print(z)

# o=np.ones((2,3))
# print(o)

# ar=np.arange(0,10,2)
# print(ar)

# l= np.linspace(1,10,5)
# print(l)

# r=np.random.randn(3,3)
# print(r)

# print("---------")

# print(a.shape)
# print(a.ndim)  #n dimension
# a.dtype
# a.size


# a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# a[1,2]
# a[0,:]
# a[:,1]
# a[1:,:2]
# a[a>8]

# #     0  1  2
# # 0  [1, 2, 3]
# # 1  [4, 5, 6]
# # 2  [7, 8, 9]


# a=np.array([1,2,3])
# b=np.array([10,20,30])
# c=np.array([9,16,25])

# a+b
# a * 2
# np.sqrt(c)
# np.dot(a,b)  # (1*10) + (2*20) + (3*30)   == 140


# m=np.ones((3,3))
# print(m)
# row=np.array((1,2,3))
# print(row)

# m+row
#   #  [2., 3., 4.],
#   #  [2., 3., 4.],
#   #  [2., 3., 4.]

a = np.array([[1,2,3],[4,5,6]])

#print(a)
np.sum(a)
np.sum(a, axis=0)   # [5, 7, 9]
np.sum(a, axis=1)   # [ 6, 15]

# [1 2 3]
# [4 5 6]

SyntaxError: positional argument follows keyword argument (3512577259.py, line 67)